baseurl = "https://http4s.org/v0.19"
contentDir = "../../target/scala-2.12/tut"
dataDir = "../../target/hugo-data"
languageCode = "en-us"
title = "http4s"
theme = "hugo-theme-learn"
themesDir = "themes"

[params]
disableInlineCopyToClipboard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "Scaladoc"
url = "/api"
weight = 10000
